# coding: utf-8

"""
    API

    ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.inline_response20042_data import InlineResponse20042Data  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20042Data(unittest.TestCase):
    """InlineResponse20042Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20042Data(self):
        """Test InlineResponse20042Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20042_data.InlineResponse20042Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
