# coding: utf-8

"""
    API

    ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.inline_response20082_last_episode_to_air import InlineResponse20082LastEpisodeToAir  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20082LastEpisodeToAir(unittest.TestCase):
    """InlineResponse20082LastEpisodeToAir unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20082LastEpisodeToAir(self):
        """Test InlineResponse20082LastEpisodeToAir"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20082_last_episode_to_air.InlineResponse20082LastEpisodeToAir()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
