# coding: utf-8

"""
    API

    ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.inline_response20051_media import InlineResponse20051Media  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20051Media(unittest.TestCase):
    """InlineResponse20051Media unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20051Media(self):
        """Test InlineResponse20051Media"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20051_media.InlineResponse20051Media()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
