# coding: utf-8

"""
    API

    ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_d_elete_authentication_session(self):
        """Test case for d_elete_authentication_session

        Delete Session  # noqa: E501
        """
        pass

    def test_d_elete_list_list_id(self):
        """Test case for d_elete_list_list_id

        Delete List  # noqa: E501
        """
        pass

    def test_d_elete_movie_movie_id_rating(self):
        """Test case for d_elete_movie_movie_id_rating

        Delete Rating  # noqa: E501
        """
        pass

    def test_d_elete_tv_tv_id_rating(self):
        """Test case for d_elete_tv_tv_id_rating

        Delete Rating  # noqa: E501
        """
        pass

    def test_d_elete_tv_tv_id_season_season_number_episode_episode_number_rating(self):
        """Test case for d_elete_tv_tv_id_season_season_number_episode_episode_number_rating

        Delete Rating  # noqa: E501
        """
        pass

    def test_g_et_account(self):
        """Test case for g_et_account

        Get Details  # noqa: E501
        """
        pass

    def test_g_et_account_account_id_favorite_movies(self):
        """Test case for g_et_account_account_id_favorite_movies

        Get Favorite Movies  # noqa: E501
        """
        pass

    def test_g_et_account_account_id_favorite_tv(self):
        """Test case for g_et_account_account_id_favorite_tv

        Get Favorite TV Shows  # noqa: E501
        """
        pass

    def test_g_et_account_account_id_lists(self):
        """Test case for g_et_account_account_id_lists

        Get Created Lists  # noqa: E501
        """
        pass

    def test_g_et_account_account_id_rated_movies(self):
        """Test case for g_et_account_account_id_rated_movies

        Get Rated Movies  # noqa: E501
        """
        pass

    def test_g_et_account_account_id_rated_tv(self):
        """Test case for g_et_account_account_id_rated_tv

        Get Rated TV Shows  # noqa: E501
        """
        pass

    def test_g_et_account_account_id_rated_tv_episodes(self):
        """Test case for g_et_account_account_id_rated_tv_episodes

        Get Rated TV Episodes  # noqa: E501
        """
        pass

    def test_g_et_account_account_id_watchlist_movies(self):
        """Test case for g_et_account_account_id_watchlist_movies

        Get Movie Watchlist  # noqa: E501
        """
        pass

    def test_g_et_account_account_id_watchlist_tv(self):
        """Test case for g_et_account_account_id_watchlist_tv

        Get TV Show Watchlist  # noqa: E501
        """
        pass

    def test_g_et_authentication_guest_session_new(self):
        """Test case for g_et_authentication_guest_session_new

        Create Guest Session  # noqa: E501
        """
        pass

    def test_g_et_authentication_token_new(self):
        """Test case for g_et_authentication_token_new

        Create Request Token  # noqa: E501
        """
        pass

    def test_g_et_certification_movie_list(self):
        """Test case for g_et_certification_movie_list

        Get Movie Certifications  # noqa: E501
        """
        pass

    def test_g_et_certification_tv_list(self):
        """Test case for g_et_certification_tv_list

        Get TV Certifications  # noqa: E501
        """
        pass

    def test_g_et_collection_collection_id(self):
        """Test case for g_et_collection_collection_id

        Get Details  # noqa: E501
        """
        pass

    def test_g_et_collection_collection_id_images(self):
        """Test case for g_et_collection_collection_id_images

        Get Images  # noqa: E501
        """
        pass

    def test_g_et_collection_collection_id_translations(self):
        """Test case for g_et_collection_collection_id_translations

        Get Translations  # noqa: E501
        """
        pass

    def test_g_et_company_company_id(self):
        """Test case for g_et_company_company_id

        Get Details  # noqa: E501
        """
        pass

    def test_g_et_company_company_id_alternative_names(self):
        """Test case for g_et_company_company_id_alternative_names

        Get Alternative Names  # noqa: E501
        """
        pass

    def test_g_et_company_company_id_images(self):
        """Test case for g_et_company_company_id_images

        Get Images  # noqa: E501
        """
        pass

    def test_g_et_configuration(self):
        """Test case for g_et_configuration

        Get API Configuration  # noqa: E501
        """
        pass

    def test_g_et_configuration_countries(self):
        """Test case for g_et_configuration_countries

        Get Countries  # noqa: E501
        """
        pass

    def test_g_et_configuration_jobs(self):
        """Test case for g_et_configuration_jobs

        Get Jobs  # noqa: E501
        """
        pass

    def test_g_et_configuration_languages(self):
        """Test case for g_et_configuration_languages

        Get Languages  # noqa: E501
        """
        pass

    def test_g_et_configuration_primary_translations(self):
        """Test case for g_et_configuration_primary_translations

        Get Primary Translations  # noqa: E501
        """
        pass

    def test_g_et_configuration_timezones(self):
        """Test case for g_et_configuration_timezones

        Get Timezones  # noqa: E501
        """
        pass

    def test_g_et_credit_credit_id(self):
        """Test case for g_et_credit_credit_id

        Get Details  # noqa: E501
        """
        pass

    def test_g_et_discover_movie(self):
        """Test case for g_et_discover_movie

        Movie Discover  # noqa: E501
        """
        pass

    def test_g_et_discover_tv(self):
        """Test case for g_et_discover_tv

        TV Discover  # noqa: E501
        """
        pass

    def test_g_et_find_external_id(self):
        """Test case for g_et_find_external_id

        Find by ID  # noqa: E501
        """
        pass

    def test_g_et_genre_movie_list(self):
        """Test case for g_et_genre_movie_list

        Get Movie List  # noqa: E501
        """
        pass

    def test_g_et_genre_tv_list(self):
        """Test case for g_et_genre_tv_list

        Get TV List  # noqa: E501
        """
        pass

    def test_g_et_guest_session_guest_session_id_rated_movies(self):
        """Test case for g_et_guest_session_guest_session_id_rated_movies

        Get Rated Movies  # noqa: E501
        """
        pass

    def test_g_et_guest_session_guest_session_id_rated_tv(self):
        """Test case for g_et_guest_session_guest_session_id_rated_tv

        Get Rated TV Shows  # noqa: E501
        """
        pass

    def test_g_et_guest_session_guest_session_id_rated_tv_episodes(self):
        """Test case for g_et_guest_session_guest_session_id_rated_tv_episodes

        Get Rated TV Episodes  # noqa: E501
        """
        pass

    def test_g_et_keyword_keyword_id(self):
        """Test case for g_et_keyword_keyword_id

        Get Details  # noqa: E501
        """
        pass

    def test_g_et_keyword_keyword_id_movies(self):
        """Test case for g_et_keyword_keyword_id_movies

        Get Movies  # noqa: E501
        """
        pass

    def test_g_et_list_list_id(self):
        """Test case for g_et_list_list_id

        Get Details  # noqa: E501
        """
        pass

    def test_g_et_list_list_id_item_status(self):
        """Test case for g_et_list_list_id_item_status

        Check Item Status  # noqa: E501
        """
        pass

    def test_g_et_movie_changes(self):
        """Test case for g_et_movie_changes

        Get Movie Change List  # noqa: E501
        """
        pass

    def test_g_et_movie_latest(self):
        """Test case for g_et_movie_latest

        Get Latest  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id(self):
        """Test case for g_et_movie_movie_id

        Get Details  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id_account_states(self):
        """Test case for g_et_movie_movie_id_account_states

        Get Account States  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id_alternative_titles(self):
        """Test case for g_et_movie_movie_id_alternative_titles

        Get Alternative Titles  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id_changes(self):
        """Test case for g_et_movie_movie_id_changes

        Get Changes  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id_credits(self):
        """Test case for g_et_movie_movie_id_credits

        Get Credits  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id_external_ids(self):
        """Test case for g_et_movie_movie_id_external_ids

        Get External IDs  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id_images(self):
        """Test case for g_et_movie_movie_id_images

        Get Images  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id_keywords(self):
        """Test case for g_et_movie_movie_id_keywords

        Get Keywords  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id_lists(self):
        """Test case for g_et_movie_movie_id_lists

        Get Lists  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id_recommendations(self):
        """Test case for g_et_movie_movie_id_recommendations

        Get Recommendations  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id_release_dates(self):
        """Test case for g_et_movie_movie_id_release_dates

        Get Release Dates  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id_reviews(self):
        """Test case for g_et_movie_movie_id_reviews

        Get Reviews  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id_similar(self):
        """Test case for g_et_movie_movie_id_similar

        Get Similar Movies  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id_translations(self):
        """Test case for g_et_movie_movie_id_translations

        Get Translations  # noqa: E501
        """
        pass

    def test_g_et_movie_movie_id_videos(self):
        """Test case for g_et_movie_movie_id_videos

        Get Videos  # noqa: E501
        """
        pass

    def test_g_et_movie_now_playing(self):
        """Test case for g_et_movie_now_playing

        Get Now Playing  # noqa: E501
        """
        pass

    def test_g_et_movie_popular(self):
        """Test case for g_et_movie_popular

        Get Popular  # noqa: E501
        """
        pass

    def test_g_et_movie_top_rated(self):
        """Test case for g_et_movie_top_rated

        Get Top Rated  # noqa: E501
        """
        pass

    def test_g_et_movie_upcoming(self):
        """Test case for g_et_movie_upcoming

        Get Upcoming  # noqa: E501
        """
        pass

    def test_g_et_network_network_id(self):
        """Test case for g_et_network_network_id

        Get Details  # noqa: E501
        """
        pass

    def test_g_et_network_network_id_alternative_names(self):
        """Test case for g_et_network_network_id_alternative_names

        Get Alternative Names  # noqa: E501
        """
        pass

    def test_g_et_network_network_id_images(self):
        """Test case for g_et_network_network_id_images

        Get Images  # noqa: E501
        """
        pass

    def test_g_et_person_changes(self):
        """Test case for g_et_person_changes

        Get Person Change List  # noqa: E501
        """
        pass

    def test_g_et_person_latest(self):
        """Test case for g_et_person_latest

        Get Latest  # noqa: E501
        """
        pass

    def test_g_et_person_person_id(self):
        """Test case for g_et_person_person_id

        Get Details  # noqa: E501
        """
        pass

    def test_g_et_person_person_id_changes(self):
        """Test case for g_et_person_person_id_changes

        Get Changes  # noqa: E501
        """
        pass

    def test_g_et_person_person_id_combined_credits(self):
        """Test case for g_et_person_person_id_combined_credits

        Get Combined Credits  # noqa: E501
        """
        pass

    def test_g_et_person_person_id_external_ids(self):
        """Test case for g_et_person_person_id_external_ids

        Get External IDs  # noqa: E501
        """
        pass

    def test_g_et_person_person_id_images(self):
        """Test case for g_et_person_person_id_images

        Get Images  # noqa: E501
        """
        pass

    def test_g_et_person_person_id_movie_credits(self):
        """Test case for g_et_person_person_id_movie_credits

        Get Movie Credits  # noqa: E501
        """
        pass

    def test_g_et_person_person_id_tagged_images(self):
        """Test case for g_et_person_person_id_tagged_images

        Get Tagged Images  # noqa: E501
        """
        pass

    def test_g_et_person_person_id_translations(self):
        """Test case for g_et_person_person_id_translations

        Get Translations  # noqa: E501
        """
        pass

    def test_g_et_person_person_id_tv_credits(self):
        """Test case for g_et_person_person_id_tv_credits

        Get TV Credits  # noqa: E501
        """
        pass

    def test_g_et_person_popular(self):
        """Test case for g_et_person_popular

        Get Popular  # noqa: E501
        """
        pass

    def test_g_et_review_review_id(self):
        """Test case for g_et_review_review_id

        Get Details  # noqa: E501
        """
        pass

    def test_g_et_search_collection(self):
        """Test case for g_et_search_collection

        Search Collections  # noqa: E501
        """
        pass

    def test_g_et_search_company(self):
        """Test case for g_et_search_company

        Search Companies  # noqa: E501
        """
        pass

    def test_g_et_search_keyword(self):
        """Test case for g_et_search_keyword

        Search Keywords  # noqa: E501
        """
        pass

    def test_g_et_search_movie(self):
        """Test case for g_et_search_movie

        Search Movies  # noqa: E501
        """
        pass

    def test_g_et_search_multi(self):
        """Test case for g_et_search_multi

        Multi Search  # noqa: E501
        """
        pass

    def test_g_et_search_person(self):
        """Test case for g_et_search_person

        Search People  # noqa: E501
        """
        pass

    def test_g_et_search_tv(self):
        """Test case for g_et_search_tv

        Search TV Shows  # noqa: E501
        """
        pass

    def test_g_et_trending_media_type_time_window(self):
        """Test case for g_et_trending_media_type_time_window

        Get Trending  # noqa: E501
        """
        pass

    def test_g_et_tv_airing_today(self):
        """Test case for g_et_tv_airing_today

        Get TV Airing Today  # noqa: E501
        """
        pass

    def test_g_et_tv_changes(self):
        """Test case for g_et_tv_changes

        Get TV Change List  # noqa: E501
        """
        pass

    def test_g_et_tv_episode_episode_id_changes(self):
        """Test case for g_et_tv_episode_episode_id_changes

        Get Changes  # noqa: E501
        """
        pass

    def test_g_et_tv_episode_group_id(self):
        """Test case for g_et_tv_episode_group_id

        Get Details  # noqa: E501
        """
        pass

    def test_g_et_tv_latest(self):
        """Test case for g_et_tv_latest

        Get Latest  # noqa: E501
        """
        pass

    def test_g_et_tv_on_the_air(self):
        """Test case for g_et_tv_on_the_air

        Get TV On The Air  # noqa: E501
        """
        pass

    def test_g_et_tv_popular(self):
        """Test case for g_et_tv_popular

        Get Popular  # noqa: E501
        """
        pass

    def test_g_et_tv_season_season_id_changes(self):
        """Test case for g_et_tv_season_season_id_changes

        Get  Changes  # noqa: E501
        """
        pass

    def test_g_et_tv_top_rated(self):
        """Test case for g_et_tv_top_rated

        Get Top Rated  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id(self):
        """Test case for g_et_tv_tv_id

        Get Details  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_account_states(self):
        """Test case for g_et_tv_tv_id_account_states

        Get Account States  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_alternative_titles(self):
        """Test case for g_et_tv_tv_id_alternative_titles

        Get Alternative Titles  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_changes(self):
        """Test case for g_et_tv_tv_id_changes

        Get Changes  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_content_ratings(self):
        """Test case for g_et_tv_tv_id_content_ratings

        Get Content Ratings  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_credits(self):
        """Test case for g_et_tv_tv_id_credits

        Get Credits  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_episode_groups(self):
        """Test case for g_et_tv_tv_id_episode_groups

        Get Episode Groups  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_external_ids(self):
        """Test case for g_et_tv_tv_id_external_ids

        Get External IDs  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_images(self):
        """Test case for g_et_tv_tv_id_images

        Get Images  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_keywords(self):
        """Test case for g_et_tv_tv_id_keywords

        Get Keywords  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_recommendations(self):
        """Test case for g_et_tv_tv_id_recommendations

        Get Recommendations  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_reviews(self):
        """Test case for g_et_tv_tv_id_reviews

        Get Reviews  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_screened_theatrically(self):
        """Test case for g_et_tv_tv_id_screened_theatrically

        Get Screened Theatrically  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_season_season_number(self):
        """Test case for g_et_tv_tv_id_season_season_number

        Get Details  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_season_season_number_account_states(self):
        """Test case for g_et_tv_tv_id_season_season_number_account_states

        Get Account States  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_season_season_number_credits(self):
        """Test case for g_et_tv_tv_id_season_season_number_credits

        Get Credits  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_season_season_number_episode_episode_number(self):
        """Test case for g_et_tv_tv_id_season_season_number_episode_episode_number

        Get Details  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_season_season_number_episode_episode_number_account_states(self):
        """Test case for g_et_tv_tv_id_season_season_number_episode_episode_number_account_states

        Get Account States  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_season_season_number_episode_episode_number_credits(self):
        """Test case for g_et_tv_tv_id_season_season_number_episode_episode_number_credits

        Get Credits  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_season_season_number_episode_episode_number_external_ids(self):
        """Test case for g_et_tv_tv_id_season_season_number_episode_episode_number_external_ids

        Get External IDs  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_season_season_number_episode_episode_number_images(self):
        """Test case for g_et_tv_tv_id_season_season_number_episode_episode_number_images

        Get Images  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_season_season_number_episode_episode_number_translations(self):
        """Test case for g_et_tv_tv_id_season_season_number_episode_episode_number_translations

        Get Translations  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_season_season_number_episode_episode_number_videos(self):
        """Test case for g_et_tv_tv_id_season_season_number_episode_episode_number_videos

        Get  Videos  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_season_season_number_external_ids(self):
        """Test case for g_et_tv_tv_id_season_season_number_external_ids

        Get External IDs  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_season_season_number_images(self):
        """Test case for g_et_tv_tv_id_season_season_number_images

        Get Images  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_season_season_number_videos(self):
        """Test case for g_et_tv_tv_id_season_season_number_videos

        Get Videos  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_similar(self):
        """Test case for g_et_tv_tv_id_similar

        Get Similar TV Shows  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_translations(self):
        """Test case for g_et_tv_tv_id_translations

        Get Translations  # noqa: E501
        """
        pass

    def test_g_et_tv_tv_id_videos(self):
        """Test case for g_et_tv_tv_id_videos

        Get Videos  # noqa: E501
        """
        pass

    def test_p_ost_account_account_id_favorite(self):
        """Test case for p_ost_account_account_id_favorite

        Mark as Favorite  # noqa: E501
        """
        pass

    def test_p_ost_account_account_id_watchlist(self):
        """Test case for p_ost_account_account_id_watchlist

        Add to Watchlist  # noqa: E501
        """
        pass

    def test_p_ost_authentication_session_convert4(self):
        """Test case for p_ost_authentication_session_convert4

        Create Session (from v4 access token)  # noqa: E501
        """
        pass

    def test_p_ost_authentication_session_new(self):
        """Test case for p_ost_authentication_session_new

        Create Session  # noqa: E501
        """
        pass

    def test_p_ost_authentication_token_validate_with_login(self):
        """Test case for p_ost_authentication_token_validate_with_login

        Create Session With Login  # noqa: E501
        """
        pass

    def test_p_ost_list(self):
        """Test case for p_ost_list

        Create List  # noqa: E501
        """
        pass

    def test_p_ost_list_list_id_add_item(self):
        """Test case for p_ost_list_list_id_add_item

        Add Movie  # noqa: E501
        """
        pass

    def test_p_ost_list_list_id_clear(self):
        """Test case for p_ost_list_list_id_clear

        Clear List  # noqa: E501
        """
        pass

    def test_p_ost_list_list_id_remove_item(self):
        """Test case for p_ost_list_list_id_remove_item

        Remove Movie  # noqa: E501
        """
        pass

    def test_p_ost_movie_movie_id_rating(self):
        """Test case for p_ost_movie_movie_id_rating

        Rate Movie  # noqa: E501
        """
        pass

    def test_p_ost_tv_tv_id_rating(self):
        """Test case for p_ost_tv_tv_id_rating

        Rate TV Show  # noqa: E501
        """
        pass

    def test_p_ost_tv_tv_id_season_season_number_episode_episode_number_rating(self):
        """Test case for p_ost_tv_tv_id_season_season_number_episode_episode_number_rating

        Rate TV Episode  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
