# coding: utf-8

"""
    API

    ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.body4 import Body4  # noqa: E501
from swagger_client.rest import ApiException


class TestBody4(unittest.TestCase):
    """Body4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody4(self):
        """Test Body4"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body4.Body4()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
