# coding: utf-8

"""
    API

    ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.inline_response20044_network import InlineResponse20044Network  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20044Network(unittest.TestCase):
    """InlineResponse20044Network unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20044Network(self):
        """Test InlineResponse20044Network"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20044_network.InlineResponse20044Network()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
