# coding: utf-8

"""
    API

    ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse20072(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'favorite': 'bool',
        'rated': 'Object',
        'watchlist': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'favorite': 'favorite',
        'rated': 'rated',
        'watchlist': 'watchlist'
    }

    def __init__(self, id=None, favorite=None, rated=None, watchlist=None):  # noqa: E501
        """InlineResponse20072 - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._favorite = None
        self._rated = None
        self._watchlist = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if favorite is not None:
            self.favorite = favorite
        if rated is not None:
            self.rated = rated
        if watchlist is not None:
            self.watchlist = watchlist

    @property
    def id(self):
        """Gets the id of this InlineResponse20072.  # noqa: E501


        :return: The id of this InlineResponse20072.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20072.


        :param id: The id of this InlineResponse20072.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def favorite(self):
        """Gets the favorite of this InlineResponse20072.  # noqa: E501


        :return: The favorite of this InlineResponse20072.  # noqa: E501
        :rtype: bool
        """
        return self._favorite

    @favorite.setter
    def favorite(self, favorite):
        """Sets the favorite of this InlineResponse20072.


        :param favorite: The favorite of this InlineResponse20072.  # noqa: E501
        :type: bool
        """

        self._favorite = favorite

    @property
    def rated(self):
        """Gets the rated of this InlineResponse20072.  # noqa: E501


        :return: The rated of this InlineResponse20072.  # noqa: E501
        :rtype: Object
        """
        return self._rated

    @rated.setter
    def rated(self, rated):
        """Sets the rated of this InlineResponse20072.


        :param rated: The rated of this InlineResponse20072.  # noqa: E501
        :type: Object
        """

        self._rated = rated

    @property
    def watchlist(self):
        """Gets the watchlist of this InlineResponse20072.  # noqa: E501


        :return: The watchlist of this InlineResponse20072.  # noqa: E501
        :rtype: bool
        """
        return self._watchlist

    @watchlist.setter
    def watchlist(self, watchlist):
        """Sets the watchlist of this InlineResponse20072.


        :param watchlist: The watchlist of this InlineResponse20072.  # noqa: E501
        :type: bool
        """

        self._watchlist = watchlist

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20072, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20072):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
