# coding: utf-8

"""
    API

    ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse20079Parts(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'adult': 'bool',
        'backdrop_path': 'Object',
        'genre_ids': 'list[int]',
        'id': 'int',
        'original_language': 'str',
        'original_title': 'str',
        'overview': 'str',
        'release_date': 'str',
        'poster_path': 'str',
        'popularity': 'float',
        'title': 'str',
        'video': 'bool',
        'vote_average': 'float',
        'vote_count': 'int'
    }

    attribute_map = {
        'adult': 'adult',
        'backdrop_path': 'backdrop_path',
        'genre_ids': 'genre_ids',
        'id': 'id',
        'original_language': 'original_language',
        'original_title': 'original_title',
        'overview': 'overview',
        'release_date': 'release_date',
        'poster_path': 'poster_path',
        'popularity': 'popularity',
        'title': 'title',
        'video': 'video',
        'vote_average': 'vote_average',
        'vote_count': 'vote_count'
    }

    def __init__(self, adult=None, backdrop_path=None, genre_ids=None, id=None, original_language=None, original_title=None, overview=None, release_date=None, poster_path=None, popularity=None, title=None, video=None, vote_average=None, vote_count=None):  # noqa: E501
        """InlineResponse20079Parts - a model defined in Swagger"""  # noqa: E501
        self._adult = None
        self._backdrop_path = None
        self._genre_ids = None
        self._id = None
        self._original_language = None
        self._original_title = None
        self._overview = None
        self._release_date = None
        self._poster_path = None
        self._popularity = None
        self._title = None
        self._video = None
        self._vote_average = None
        self._vote_count = None
        self.discriminator = None
        if adult is not None:
            self.adult = adult
        if backdrop_path is not None:
            self.backdrop_path = backdrop_path
        if genre_ids is not None:
            self.genre_ids = genre_ids
        if id is not None:
            self.id = id
        if original_language is not None:
            self.original_language = original_language
        if original_title is not None:
            self.original_title = original_title
        if overview is not None:
            self.overview = overview
        if release_date is not None:
            self.release_date = release_date
        if poster_path is not None:
            self.poster_path = poster_path
        if popularity is not None:
            self.popularity = popularity
        if title is not None:
            self.title = title
        if video is not None:
            self.video = video
        if vote_average is not None:
            self.vote_average = vote_average
        if vote_count is not None:
            self.vote_count = vote_count

    @property
    def adult(self):
        """Gets the adult of this InlineResponse20079Parts.  # noqa: E501


        :return: The adult of this InlineResponse20079Parts.  # noqa: E501
        :rtype: bool
        """
        return self._adult

    @adult.setter
    def adult(self, adult):
        """Sets the adult of this InlineResponse20079Parts.


        :param adult: The adult of this InlineResponse20079Parts.  # noqa: E501
        :type: bool
        """

        self._adult = adult

    @property
    def backdrop_path(self):
        """Gets the backdrop_path of this InlineResponse20079Parts.  # noqa: E501


        :return: The backdrop_path of this InlineResponse20079Parts.  # noqa: E501
        :rtype: Object
        """
        return self._backdrop_path

    @backdrop_path.setter
    def backdrop_path(self, backdrop_path):
        """Sets the backdrop_path of this InlineResponse20079Parts.


        :param backdrop_path: The backdrop_path of this InlineResponse20079Parts.  # noqa: E501
        :type: Object
        """

        self._backdrop_path = backdrop_path

    @property
    def genre_ids(self):
        """Gets the genre_ids of this InlineResponse20079Parts.  # noqa: E501


        :return: The genre_ids of this InlineResponse20079Parts.  # noqa: E501
        :rtype: list[int]
        """
        return self._genre_ids

    @genre_ids.setter
    def genre_ids(self, genre_ids):
        """Sets the genre_ids of this InlineResponse20079Parts.


        :param genre_ids: The genre_ids of this InlineResponse20079Parts.  # noqa: E501
        :type: list[int]
        """

        self._genre_ids = genre_ids

    @property
    def id(self):
        """Gets the id of this InlineResponse20079Parts.  # noqa: E501


        :return: The id of this InlineResponse20079Parts.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20079Parts.


        :param id: The id of this InlineResponse20079Parts.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def original_language(self):
        """Gets the original_language of this InlineResponse20079Parts.  # noqa: E501


        :return: The original_language of this InlineResponse20079Parts.  # noqa: E501
        :rtype: str
        """
        return self._original_language

    @original_language.setter
    def original_language(self, original_language):
        """Sets the original_language of this InlineResponse20079Parts.


        :param original_language: The original_language of this InlineResponse20079Parts.  # noqa: E501
        :type: str
        """

        self._original_language = original_language

    @property
    def original_title(self):
        """Gets the original_title of this InlineResponse20079Parts.  # noqa: E501


        :return: The original_title of this InlineResponse20079Parts.  # noqa: E501
        :rtype: str
        """
        return self._original_title

    @original_title.setter
    def original_title(self, original_title):
        """Sets the original_title of this InlineResponse20079Parts.


        :param original_title: The original_title of this InlineResponse20079Parts.  # noqa: E501
        :type: str
        """

        self._original_title = original_title

    @property
    def overview(self):
        """Gets the overview of this InlineResponse20079Parts.  # noqa: E501


        :return: The overview of this InlineResponse20079Parts.  # noqa: E501
        :rtype: str
        """
        return self._overview

    @overview.setter
    def overview(self, overview):
        """Sets the overview of this InlineResponse20079Parts.


        :param overview: The overview of this InlineResponse20079Parts.  # noqa: E501
        :type: str
        """

        self._overview = overview

    @property
    def release_date(self):
        """Gets the release_date of this InlineResponse20079Parts.  # noqa: E501


        :return: The release_date of this InlineResponse20079Parts.  # noqa: E501
        :rtype: str
        """
        return self._release_date

    @release_date.setter
    def release_date(self, release_date):
        """Sets the release_date of this InlineResponse20079Parts.


        :param release_date: The release_date of this InlineResponse20079Parts.  # noqa: E501
        :type: str
        """

        self._release_date = release_date

    @property
    def poster_path(self):
        """Gets the poster_path of this InlineResponse20079Parts.  # noqa: E501


        :return: The poster_path of this InlineResponse20079Parts.  # noqa: E501
        :rtype: str
        """
        return self._poster_path

    @poster_path.setter
    def poster_path(self, poster_path):
        """Sets the poster_path of this InlineResponse20079Parts.


        :param poster_path: The poster_path of this InlineResponse20079Parts.  # noqa: E501
        :type: str
        """

        self._poster_path = poster_path

    @property
    def popularity(self):
        """Gets the popularity of this InlineResponse20079Parts.  # noqa: E501


        :return: The popularity of this InlineResponse20079Parts.  # noqa: E501
        :rtype: float
        """
        return self._popularity

    @popularity.setter
    def popularity(self, popularity):
        """Sets the popularity of this InlineResponse20079Parts.


        :param popularity: The popularity of this InlineResponse20079Parts.  # noqa: E501
        :type: float
        """

        self._popularity = popularity

    @property
    def title(self):
        """Gets the title of this InlineResponse20079Parts.  # noqa: E501


        :return: The title of this InlineResponse20079Parts.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this InlineResponse20079Parts.


        :param title: The title of this InlineResponse20079Parts.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def video(self):
        """Gets the video of this InlineResponse20079Parts.  # noqa: E501


        :return: The video of this InlineResponse20079Parts.  # noqa: E501
        :rtype: bool
        """
        return self._video

    @video.setter
    def video(self, video):
        """Sets the video of this InlineResponse20079Parts.


        :param video: The video of this InlineResponse20079Parts.  # noqa: E501
        :type: bool
        """

        self._video = video

    @property
    def vote_average(self):
        """Gets the vote_average of this InlineResponse20079Parts.  # noqa: E501


        :return: The vote_average of this InlineResponse20079Parts.  # noqa: E501
        :rtype: float
        """
        return self._vote_average

    @vote_average.setter
    def vote_average(self, vote_average):
        """Sets the vote_average of this InlineResponse20079Parts.


        :param vote_average: The vote_average of this InlineResponse20079Parts.  # noqa: E501
        :type: float
        """

        self._vote_average = vote_average

    @property
    def vote_count(self):
        """Gets the vote_count of this InlineResponse20079Parts.  # noqa: E501


        :return: The vote_count of this InlineResponse20079Parts.  # noqa: E501
        :rtype: int
        """
        return self._vote_count

    @vote_count.setter
    def vote_count(self, vote_count):
        """Sets the vote_count of this InlineResponse20079Parts.


        :param vote_count: The vote_count of this InlineResponse20079Parts.  # noqa: E501
        :type: int
        """

        self._vote_count = vote_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20079Parts, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20079Parts):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
