# coding: utf-8

"""
    API

    ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse20033GuestStars(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'credit_id': 'str',
        'character': 'str',
        'order': 'int',
        'profile_path': 'ImagePath'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'credit_id': 'credit_id',
        'character': 'character',
        'order': 'order',
        'profile_path': 'profile_path'
    }

    def __init__(self, id=None, name=None, credit_id=None, character=None, order=None, profile_path=None):  # noqa: E501
        """InlineResponse20033GuestStars - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._credit_id = None
        self._character = None
        self._order = None
        self._profile_path = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if credit_id is not None:
            self.credit_id = credit_id
        if character is not None:
            self.character = character
        if order is not None:
            self.order = order
        if profile_path is not None:
            self.profile_path = profile_path

    @property
    def id(self):
        """Gets the id of this InlineResponse20033GuestStars.  # noqa: E501


        :return: The id of this InlineResponse20033GuestStars.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20033GuestStars.


        :param id: The id of this InlineResponse20033GuestStars.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this InlineResponse20033GuestStars.  # noqa: E501


        :return: The name of this InlineResponse20033GuestStars.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse20033GuestStars.


        :param name: The name of this InlineResponse20033GuestStars.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def credit_id(self):
        """Gets the credit_id of this InlineResponse20033GuestStars.  # noqa: E501


        :return: The credit_id of this InlineResponse20033GuestStars.  # noqa: E501
        :rtype: str
        """
        return self._credit_id

    @credit_id.setter
    def credit_id(self, credit_id):
        """Sets the credit_id of this InlineResponse20033GuestStars.


        :param credit_id: The credit_id of this InlineResponse20033GuestStars.  # noqa: E501
        :type: str
        """

        self._credit_id = credit_id

    @property
    def character(self):
        """Gets the character of this InlineResponse20033GuestStars.  # noqa: E501


        :return: The character of this InlineResponse20033GuestStars.  # noqa: E501
        :rtype: str
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this InlineResponse20033GuestStars.


        :param character: The character of this InlineResponse20033GuestStars.  # noqa: E501
        :type: str
        """

        self._character = character

    @property
    def order(self):
        """Gets the order of this InlineResponse20033GuestStars.  # noqa: E501


        :return: The order of this InlineResponse20033GuestStars.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this InlineResponse20033GuestStars.


        :param order: The order of this InlineResponse20033GuestStars.  # noqa: E501
        :type: int
        """

        self._order = order

    @property
    def profile_path(self):
        """Gets the profile_path of this InlineResponse20033GuestStars.  # noqa: E501


        :return: The profile_path of this InlineResponse20033GuestStars.  # noqa: E501
        :rtype: ImagePath
        """
        return self._profile_path

    @profile_path.setter
    def profile_path(self, profile_path):
        """Sets the profile_path of this InlineResponse20033GuestStars.


        :param profile_path: The profile_path of this InlineResponse20033GuestStars.  # noqa: E501
        :type: ImagePath
        """

        self._profile_path = profile_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20033GuestStars, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20033GuestStars):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
