# coding: utf-8

"""
    API

    ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse20043Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'overview': 'str',
        'homepage': 'str'
    }

    attribute_map = {
        'title': 'title',
        'overview': 'overview',
        'homepage': 'homepage'
    }

    def __init__(self, title=None, overview=None, homepage=None):  # noqa: E501
        """InlineResponse20043Data - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._overview = None
        self._homepage = None
        self.discriminator = None
        if title is not None:
            self.title = title
        if overview is not None:
            self.overview = overview
        if homepage is not None:
            self.homepage = homepage

    @property
    def title(self):
        """Gets the title of this InlineResponse20043Data.  # noqa: E501


        :return: The title of this InlineResponse20043Data.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this InlineResponse20043Data.


        :param title: The title of this InlineResponse20043Data.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def overview(self):
        """Gets the overview of this InlineResponse20043Data.  # noqa: E501


        :return: The overview of this InlineResponse20043Data.  # noqa: E501
        :rtype: str
        """
        return self._overview

    @overview.setter
    def overview(self, overview):
        """Sets the overview of this InlineResponse20043Data.


        :param overview: The overview of this InlineResponse20043Data.  # noqa: E501
        :type: str
        """

        self._overview = overview

    @property
    def homepage(self):
        """Gets the homepage of this InlineResponse20043Data.  # noqa: E501


        :return: The homepage of this InlineResponse20043Data.  # noqa: E501
        :rtype: str
        """
        return self._homepage

    @homepage.setter
    def homepage(self, homepage):
        """Sets the homepage of this InlineResponse20043Data.


        :param homepage: The homepage of this InlineResponse20043Data.  # noqa: E501
        :type: str
        """

        self._homepage = homepage

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20043Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20043Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
