# coding: utf-8

"""
    API

    ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse20038(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_by': 'str',
        'description': 'str',
        'favorite_count': 'int',
        'id': 'str',
        'items': 'list[MovieListObject]',
        'item_count': 'int',
        'iso_639_1': 'str',
        'name': 'str',
        'poster_path': 'ImagePath'
    }

    attribute_map = {
        'created_by': 'created_by',
        'description': 'description',
        'favorite_count': 'favorite_count',
        'id': 'id',
        'items': 'items',
        'item_count': 'item_count',
        'iso_639_1': 'iso_639_1',
        'name': 'name',
        'poster_path': 'poster_path'
    }

    def __init__(self, created_by=None, description=None, favorite_count=None, id=None, items=None, item_count=None, iso_639_1=None, name=None, poster_path=None):  # noqa: E501
        """InlineResponse20038 - a model defined in Swagger"""  # noqa: E501
        self._created_by = None
        self._description = None
        self._favorite_count = None
        self._id = None
        self._items = None
        self._item_count = None
        self._iso_639_1 = None
        self._name = None
        self._poster_path = None
        self.discriminator = None
        if created_by is not None:
            self.created_by = created_by
        if description is not None:
            self.description = description
        if favorite_count is not None:
            self.favorite_count = favorite_count
        if id is not None:
            self.id = id
        if items is not None:
            self.items = items
        if item_count is not None:
            self.item_count = item_count
        if iso_639_1 is not None:
            self.iso_639_1 = iso_639_1
        if name is not None:
            self.name = name
        if poster_path is not None:
            self.poster_path = poster_path

    @property
    def created_by(self):
        """Gets the created_by of this InlineResponse20038.  # noqa: E501


        :return: The created_by of this InlineResponse20038.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this InlineResponse20038.


        :param created_by: The created_by of this InlineResponse20038.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def description(self):
        """Gets the description of this InlineResponse20038.  # noqa: E501


        :return: The description of this InlineResponse20038.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InlineResponse20038.


        :param description: The description of this InlineResponse20038.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def favorite_count(self):
        """Gets the favorite_count of this InlineResponse20038.  # noqa: E501


        :return: The favorite_count of this InlineResponse20038.  # noqa: E501
        :rtype: int
        """
        return self._favorite_count

    @favorite_count.setter
    def favorite_count(self, favorite_count):
        """Sets the favorite_count of this InlineResponse20038.


        :param favorite_count: The favorite_count of this InlineResponse20038.  # noqa: E501
        :type: int
        """

        self._favorite_count = favorite_count

    @property
    def id(self):
        """Gets the id of this InlineResponse20038.  # noqa: E501


        :return: The id of this InlineResponse20038.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20038.


        :param id: The id of this InlineResponse20038.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def items(self):
        """Gets the items of this InlineResponse20038.  # noqa: E501


        :return: The items of this InlineResponse20038.  # noqa: E501
        :rtype: list[MovieListObject]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this InlineResponse20038.


        :param items: The items of this InlineResponse20038.  # noqa: E501
        :type: list[MovieListObject]
        """

        self._items = items

    @property
    def item_count(self):
        """Gets the item_count of this InlineResponse20038.  # noqa: E501


        :return: The item_count of this InlineResponse20038.  # noqa: E501
        :rtype: int
        """
        return self._item_count

    @item_count.setter
    def item_count(self, item_count):
        """Sets the item_count of this InlineResponse20038.


        :param item_count: The item_count of this InlineResponse20038.  # noqa: E501
        :type: int
        """

        self._item_count = item_count

    @property
    def iso_639_1(self):
        """Gets the iso_639_1 of this InlineResponse20038.  # noqa: E501


        :return: The iso_639_1 of this InlineResponse20038.  # noqa: E501
        :rtype: str
        """
        return self._iso_639_1

    @iso_639_1.setter
    def iso_639_1(self, iso_639_1):
        """Sets the iso_639_1 of this InlineResponse20038.


        :param iso_639_1: The iso_639_1 of this InlineResponse20038.  # noqa: E501
        :type: str
        """

        self._iso_639_1 = iso_639_1

    @property
    def name(self):
        """Gets the name of this InlineResponse20038.  # noqa: E501


        :return: The name of this InlineResponse20038.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse20038.


        :param name: The name of this InlineResponse20038.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def poster_path(self):
        """Gets the poster_path of this InlineResponse20038.  # noqa: E501


        :return: The poster_path of this InlineResponse20038.  # noqa: E501
        :rtype: ImagePath
        """
        return self._poster_path

    @poster_path.setter
    def poster_path(self, poster_path):
        """Sets the poster_path of this InlineResponse20038.


        :param poster_path: The poster_path of this InlineResponse20038.  # noqa: E501
        :type: ImagePath
        """

        self._poster_path = poster_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20038, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20038):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
