# coding: utf-8

"""
    API

    ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse20070(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'adult': 'bool',
        'backdrop_path': 'ImagePath',
        'belongs_to_collection': 'Object',
        'budget': 'int',
        'genres': 'list[InlineResponse20018Results]',
        'homepage': 'str',
        'id': 'int',
        'imdb_id': 'str',
        'original_language': 'str',
        'original_title': 'str',
        'overview': 'str',
        'popularity': 'int',
        'poster_path': 'ImagePath',
        'production_companies': 'list[object]',
        'production_countries': 'list[object]',
        'release_date': 'str',
        'revenue': 'int',
        'runtime': 'int',
        'spoken_languages': 'list[object]',
        'status': 'str',
        'tagline': 'str',
        'title': 'str',
        'video': 'bool',
        'vote_average': 'int',
        'vote_count': 'int'
    }

    attribute_map = {
        'adult': 'adult',
        'backdrop_path': 'backdrop_path',
        'belongs_to_collection': 'belongs_to_collection',
        'budget': 'budget',
        'genres': 'genres',
        'homepage': 'homepage',
        'id': 'id',
        'imdb_id': 'imdb_id',
        'original_language': 'original_language',
        'original_title': 'original_title',
        'overview': 'overview',
        'popularity': 'popularity',
        'poster_path': 'poster_path',
        'production_companies': 'production_companies',
        'production_countries': 'production_countries',
        'release_date': 'release_date',
        'revenue': 'revenue',
        'runtime': 'runtime',
        'spoken_languages': 'spoken_languages',
        'status': 'status',
        'tagline': 'tagline',
        'title': 'title',
        'video': 'video',
        'vote_average': 'vote_average',
        'vote_count': 'vote_count'
    }

    def __init__(self, adult=None, backdrop_path=None, belongs_to_collection=None, budget=None, genres=None, homepage=None, id=None, imdb_id=None, original_language=None, original_title=None, overview=None, popularity=None, poster_path=None, production_companies=None, production_countries=None, release_date=None, revenue=None, runtime=None, spoken_languages=None, status=None, tagline=None, title=None, video=None, vote_average=None, vote_count=None):  # noqa: E501
        """InlineResponse20070 - a model defined in Swagger"""  # noqa: E501
        self._adult = None
        self._backdrop_path = None
        self._belongs_to_collection = None
        self._budget = None
        self._genres = None
        self._homepage = None
        self._id = None
        self._imdb_id = None
        self._original_language = None
        self._original_title = None
        self._overview = None
        self._popularity = None
        self._poster_path = None
        self._production_companies = None
        self._production_countries = None
        self._release_date = None
        self._revenue = None
        self._runtime = None
        self._spoken_languages = None
        self._status = None
        self._tagline = None
        self._title = None
        self._video = None
        self._vote_average = None
        self._vote_count = None
        self.discriminator = None
        if adult is not None:
            self.adult = adult
        if backdrop_path is not None:
            self.backdrop_path = backdrop_path
        if belongs_to_collection is not None:
            self.belongs_to_collection = belongs_to_collection
        if budget is not None:
            self.budget = budget
        if genres is not None:
            self.genres = genres
        if homepage is not None:
            self.homepage = homepage
        if id is not None:
            self.id = id
        if imdb_id is not None:
            self.imdb_id = imdb_id
        if original_language is not None:
            self.original_language = original_language
        if original_title is not None:
            self.original_title = original_title
        if overview is not None:
            self.overview = overview
        if popularity is not None:
            self.popularity = popularity
        if poster_path is not None:
            self.poster_path = poster_path
        if production_companies is not None:
            self.production_companies = production_companies
        if production_countries is not None:
            self.production_countries = production_countries
        if release_date is not None:
            self.release_date = release_date
        if revenue is not None:
            self.revenue = revenue
        if runtime is not None:
            self.runtime = runtime
        if spoken_languages is not None:
            self.spoken_languages = spoken_languages
        if status is not None:
            self.status = status
        if tagline is not None:
            self.tagline = tagline
        if title is not None:
            self.title = title
        if video is not None:
            self.video = video
        if vote_average is not None:
            self.vote_average = vote_average
        if vote_count is not None:
            self.vote_count = vote_count

    @property
    def adult(self):
        """Gets the adult of this InlineResponse20070.  # noqa: E501


        :return: The adult of this InlineResponse20070.  # noqa: E501
        :rtype: bool
        """
        return self._adult

    @adult.setter
    def adult(self, adult):
        """Sets the adult of this InlineResponse20070.


        :param adult: The adult of this InlineResponse20070.  # noqa: E501
        :type: bool
        """

        self._adult = adult

    @property
    def backdrop_path(self):
        """Gets the backdrop_path of this InlineResponse20070.  # noqa: E501


        :return: The backdrop_path of this InlineResponse20070.  # noqa: E501
        :rtype: ImagePath
        """
        return self._backdrop_path

    @backdrop_path.setter
    def backdrop_path(self, backdrop_path):
        """Sets the backdrop_path of this InlineResponse20070.


        :param backdrop_path: The backdrop_path of this InlineResponse20070.  # noqa: E501
        :type: ImagePath
        """

        self._backdrop_path = backdrop_path

    @property
    def belongs_to_collection(self):
        """Gets the belongs_to_collection of this InlineResponse20070.  # noqa: E501


        :return: The belongs_to_collection of this InlineResponse20070.  # noqa: E501
        :rtype: Object
        """
        return self._belongs_to_collection

    @belongs_to_collection.setter
    def belongs_to_collection(self, belongs_to_collection):
        """Sets the belongs_to_collection of this InlineResponse20070.


        :param belongs_to_collection: The belongs_to_collection of this InlineResponse20070.  # noqa: E501
        :type: Object
        """

        self._belongs_to_collection = belongs_to_collection

    @property
    def budget(self):
        """Gets the budget of this InlineResponse20070.  # noqa: E501


        :return: The budget of this InlineResponse20070.  # noqa: E501
        :rtype: int
        """
        return self._budget

    @budget.setter
    def budget(self, budget):
        """Sets the budget of this InlineResponse20070.


        :param budget: The budget of this InlineResponse20070.  # noqa: E501
        :type: int
        """

        self._budget = budget

    @property
    def genres(self):
        """Gets the genres of this InlineResponse20070.  # noqa: E501


        :return: The genres of this InlineResponse20070.  # noqa: E501
        :rtype: list[InlineResponse20018Results]
        """
        return self._genres

    @genres.setter
    def genres(self, genres):
        """Sets the genres of this InlineResponse20070.


        :param genres: The genres of this InlineResponse20070.  # noqa: E501
        :type: list[InlineResponse20018Results]
        """

        self._genres = genres

    @property
    def homepage(self):
        """Gets the homepage of this InlineResponse20070.  # noqa: E501


        :return: The homepage of this InlineResponse20070.  # noqa: E501
        :rtype: str
        """
        return self._homepage

    @homepage.setter
    def homepage(self, homepage):
        """Sets the homepage of this InlineResponse20070.


        :param homepage: The homepage of this InlineResponse20070.  # noqa: E501
        :type: str
        """

        self._homepage = homepage

    @property
    def id(self):
        """Gets the id of this InlineResponse20070.  # noqa: E501


        :return: The id of this InlineResponse20070.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20070.


        :param id: The id of this InlineResponse20070.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def imdb_id(self):
        """Gets the imdb_id of this InlineResponse20070.  # noqa: E501


        :return: The imdb_id of this InlineResponse20070.  # noqa: E501
        :rtype: str
        """
        return self._imdb_id

    @imdb_id.setter
    def imdb_id(self, imdb_id):
        """Sets the imdb_id of this InlineResponse20070.


        :param imdb_id: The imdb_id of this InlineResponse20070.  # noqa: E501
        :type: str
        """

        self._imdb_id = imdb_id

    @property
    def original_language(self):
        """Gets the original_language of this InlineResponse20070.  # noqa: E501


        :return: The original_language of this InlineResponse20070.  # noqa: E501
        :rtype: str
        """
        return self._original_language

    @original_language.setter
    def original_language(self, original_language):
        """Sets the original_language of this InlineResponse20070.


        :param original_language: The original_language of this InlineResponse20070.  # noqa: E501
        :type: str
        """

        self._original_language = original_language

    @property
    def original_title(self):
        """Gets the original_title of this InlineResponse20070.  # noqa: E501


        :return: The original_title of this InlineResponse20070.  # noqa: E501
        :rtype: str
        """
        return self._original_title

    @original_title.setter
    def original_title(self, original_title):
        """Sets the original_title of this InlineResponse20070.


        :param original_title: The original_title of this InlineResponse20070.  # noqa: E501
        :type: str
        """

        self._original_title = original_title

    @property
    def overview(self):
        """Gets the overview of this InlineResponse20070.  # noqa: E501


        :return: The overview of this InlineResponse20070.  # noqa: E501
        :rtype: str
        """
        return self._overview

    @overview.setter
    def overview(self, overview):
        """Sets the overview of this InlineResponse20070.


        :param overview: The overview of this InlineResponse20070.  # noqa: E501
        :type: str
        """

        self._overview = overview

    @property
    def popularity(self):
        """Gets the popularity of this InlineResponse20070.  # noqa: E501


        :return: The popularity of this InlineResponse20070.  # noqa: E501
        :rtype: int
        """
        return self._popularity

    @popularity.setter
    def popularity(self, popularity):
        """Sets the popularity of this InlineResponse20070.


        :param popularity: The popularity of this InlineResponse20070.  # noqa: E501
        :type: int
        """

        self._popularity = popularity

    @property
    def poster_path(self):
        """Gets the poster_path of this InlineResponse20070.  # noqa: E501


        :return: The poster_path of this InlineResponse20070.  # noqa: E501
        :rtype: ImagePath
        """
        return self._poster_path

    @poster_path.setter
    def poster_path(self, poster_path):
        """Sets the poster_path of this InlineResponse20070.


        :param poster_path: The poster_path of this InlineResponse20070.  # noqa: E501
        :type: ImagePath
        """

        self._poster_path = poster_path

    @property
    def production_companies(self):
        """Gets the production_companies of this InlineResponse20070.  # noqa: E501


        :return: The production_companies of this InlineResponse20070.  # noqa: E501
        :rtype: list[object]
        """
        return self._production_companies

    @production_companies.setter
    def production_companies(self, production_companies):
        """Sets the production_companies of this InlineResponse20070.


        :param production_companies: The production_companies of this InlineResponse20070.  # noqa: E501
        :type: list[object]
        """

        self._production_companies = production_companies

    @property
    def production_countries(self):
        """Gets the production_countries of this InlineResponse20070.  # noqa: E501


        :return: The production_countries of this InlineResponse20070.  # noqa: E501
        :rtype: list[object]
        """
        return self._production_countries

    @production_countries.setter
    def production_countries(self, production_countries):
        """Sets the production_countries of this InlineResponse20070.


        :param production_countries: The production_countries of this InlineResponse20070.  # noqa: E501
        :type: list[object]
        """

        self._production_countries = production_countries

    @property
    def release_date(self):
        """Gets the release_date of this InlineResponse20070.  # noqa: E501


        :return: The release_date of this InlineResponse20070.  # noqa: E501
        :rtype: str
        """
        return self._release_date

    @release_date.setter
    def release_date(self, release_date):
        """Sets the release_date of this InlineResponse20070.


        :param release_date: The release_date of this InlineResponse20070.  # noqa: E501
        :type: str
        """

        self._release_date = release_date

    @property
    def revenue(self):
        """Gets the revenue of this InlineResponse20070.  # noqa: E501


        :return: The revenue of this InlineResponse20070.  # noqa: E501
        :rtype: int
        """
        return self._revenue

    @revenue.setter
    def revenue(self, revenue):
        """Sets the revenue of this InlineResponse20070.


        :param revenue: The revenue of this InlineResponse20070.  # noqa: E501
        :type: int
        """

        self._revenue = revenue

    @property
    def runtime(self):
        """Gets the runtime of this InlineResponse20070.  # noqa: E501


        :return: The runtime of this InlineResponse20070.  # noqa: E501
        :rtype: int
        """
        return self._runtime

    @runtime.setter
    def runtime(self, runtime):
        """Sets the runtime of this InlineResponse20070.


        :param runtime: The runtime of this InlineResponse20070.  # noqa: E501
        :type: int
        """

        self._runtime = runtime

    @property
    def spoken_languages(self):
        """Gets the spoken_languages of this InlineResponse20070.  # noqa: E501


        :return: The spoken_languages of this InlineResponse20070.  # noqa: E501
        :rtype: list[object]
        """
        return self._spoken_languages

    @spoken_languages.setter
    def spoken_languages(self, spoken_languages):
        """Sets the spoken_languages of this InlineResponse20070.


        :param spoken_languages: The spoken_languages of this InlineResponse20070.  # noqa: E501
        :type: list[object]
        """

        self._spoken_languages = spoken_languages

    @property
    def status(self):
        """Gets the status of this InlineResponse20070.  # noqa: E501


        :return: The status of this InlineResponse20070.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20070.


        :param status: The status of this InlineResponse20070.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def tagline(self):
        """Gets the tagline of this InlineResponse20070.  # noqa: E501


        :return: The tagline of this InlineResponse20070.  # noqa: E501
        :rtype: str
        """
        return self._tagline

    @tagline.setter
    def tagline(self, tagline):
        """Sets the tagline of this InlineResponse20070.


        :param tagline: The tagline of this InlineResponse20070.  # noqa: E501
        :type: str
        """

        self._tagline = tagline

    @property
    def title(self):
        """Gets the title of this InlineResponse20070.  # noqa: E501


        :return: The title of this InlineResponse20070.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this InlineResponse20070.


        :param title: The title of this InlineResponse20070.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def video(self):
        """Gets the video of this InlineResponse20070.  # noqa: E501


        :return: The video of this InlineResponse20070.  # noqa: E501
        :rtype: bool
        """
        return self._video

    @video.setter
    def video(self, video):
        """Sets the video of this InlineResponse20070.


        :param video: The video of this InlineResponse20070.  # noqa: E501
        :type: bool
        """

        self._video = video

    @property
    def vote_average(self):
        """Gets the vote_average of this InlineResponse20070.  # noqa: E501


        :return: The vote_average of this InlineResponse20070.  # noqa: E501
        :rtype: int
        """
        return self._vote_average

    @vote_average.setter
    def vote_average(self, vote_average):
        """Sets the vote_average of this InlineResponse20070.


        :param vote_average: The vote_average of this InlineResponse20070.  # noqa: E501
        :type: int
        """

        self._vote_average = vote_average

    @property
    def vote_count(self):
        """Gets the vote_count of this InlineResponse20070.  # noqa: E501


        :return: The vote_count of this InlineResponse20070.  # noqa: E501
        :rtype: int
        """
        return self._vote_count

    @vote_count.setter
    def vote_count(self, vote_count):
        """Sets the vote_count of this InlineResponse20070.


        :param vote_count: The vote_count of this InlineResponse20070.  # noqa: E501
        :type: int
        """

        self._vote_count = vote_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20070, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20070):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
