# coding: utf-8

"""
    API

    ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse20095(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'air_date': 'str',
        'episodes': 'list[InlineResponse20095Episodes]',
        'name': 'str',
        'overview': 'str',
        'id': 'int',
        'poster_path': 'ImagePath',
        'season_number': 'int'
    }

    attribute_map = {
        'id': '_id',
        'air_date': 'air_date',
        'episodes': 'episodes',
        'name': 'name',
        'overview': 'overview',
        'id': 'id',
        'poster_path': 'poster_path',
        'season_number': 'season_number'
    }

    def __init__(self, id=None, air_date=None, episodes=None, name=None, overview=None, id=None, poster_path=None, season_number=None):  # noqa: E501
        """InlineResponse20095 - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._air_date = None
        self._episodes = None
        self._name = None
        self._overview = None
        self._id = None
        self._poster_path = None
        self._season_number = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if air_date is not None:
            self.air_date = air_date
        if episodes is not None:
            self.episodes = episodes
        if name is not None:
            self.name = name
        if overview is not None:
            self.overview = overview
        if id is not None:
            self.id = id
        if poster_path is not None:
            self.poster_path = poster_path
        if season_number is not None:
            self.season_number = season_number

    @property
    def id(self):
        """Gets the id of this InlineResponse20095.  # noqa: E501


        :return: The id of this InlineResponse20095.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20095.


        :param id: The id of this InlineResponse20095.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def air_date(self):
        """Gets the air_date of this InlineResponse20095.  # noqa: E501


        :return: The air_date of this InlineResponse20095.  # noqa: E501
        :rtype: str
        """
        return self._air_date

    @air_date.setter
    def air_date(self, air_date):
        """Sets the air_date of this InlineResponse20095.


        :param air_date: The air_date of this InlineResponse20095.  # noqa: E501
        :type: str
        """

        self._air_date = air_date

    @property
    def episodes(self):
        """Gets the episodes of this InlineResponse20095.  # noqa: E501


        :return: The episodes of this InlineResponse20095.  # noqa: E501
        :rtype: list[InlineResponse20095Episodes]
        """
        return self._episodes

    @episodes.setter
    def episodes(self, episodes):
        """Sets the episodes of this InlineResponse20095.


        :param episodes: The episodes of this InlineResponse20095.  # noqa: E501
        :type: list[InlineResponse20095Episodes]
        """

        self._episodes = episodes

    @property
    def name(self):
        """Gets the name of this InlineResponse20095.  # noqa: E501


        :return: The name of this InlineResponse20095.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse20095.


        :param name: The name of this InlineResponse20095.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def overview(self):
        """Gets the overview of this InlineResponse20095.  # noqa: E501


        :return: The overview of this InlineResponse20095.  # noqa: E501
        :rtype: str
        """
        return self._overview

    @overview.setter
    def overview(self, overview):
        """Sets the overview of this InlineResponse20095.


        :param overview: The overview of this InlineResponse20095.  # noqa: E501
        :type: str
        """

        self._overview = overview

    @property
    def id(self):
        """Gets the id of this InlineResponse20095.  # noqa: E501


        :return: The id of this InlineResponse20095.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20095.


        :param id: The id of this InlineResponse20095.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def poster_path(self):
        """Gets the poster_path of this InlineResponse20095.  # noqa: E501


        :return: The poster_path of this InlineResponse20095.  # noqa: E501
        :rtype: ImagePath
        """
        return self._poster_path

    @poster_path.setter
    def poster_path(self, poster_path):
        """Sets the poster_path of this InlineResponse20095.


        :param poster_path: The poster_path of this InlineResponse20095.  # noqa: E501
        :type: ImagePath
        """

        self._poster_path = poster_path

    @property
    def season_number(self):
        """Gets the season_number of this InlineResponse20095.  # noqa: E501


        :return: The season_number of this InlineResponse20095.  # noqa: E501
        :rtype: int
        """
        return self._season_number

    @season_number.setter
    def season_number(self, season_number):
        """Sets the season_number of this InlineResponse20095.


        :param season_number: The season_number of this InlineResponse20095.  # noqa: E501
        :type: int
        """

        self._season_number = season_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20095, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20095):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
