# coding: utf-8

"""
    API

    ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse2007(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'iso_639_1': 'str',
        'english_name': 'str',
        'name': 'str'
    }

    attribute_map = {
        'iso_639_1': 'iso_639_1',
        'english_name': 'english_name',
        'name': 'name'
    }

    def __init__(self, iso_639_1=None, english_name=None, name=None):  # noqa: E501
        """InlineResponse2007 - a model defined in Swagger"""  # noqa: E501
        self._iso_639_1 = None
        self._english_name = None
        self._name = None
        self.discriminator = None
        if iso_639_1 is not None:
            self.iso_639_1 = iso_639_1
        if english_name is not None:
            self.english_name = english_name
        if name is not None:
            self.name = name

    @property
    def iso_639_1(self):
        """Gets the iso_639_1 of this InlineResponse2007.  # noqa: E501


        :return: The iso_639_1 of this InlineResponse2007.  # noqa: E501
        :rtype: str
        """
        return self._iso_639_1

    @iso_639_1.setter
    def iso_639_1(self, iso_639_1):
        """Sets the iso_639_1 of this InlineResponse2007.


        :param iso_639_1: The iso_639_1 of this InlineResponse2007.  # noqa: E501
        :type: str
        """

        self._iso_639_1 = iso_639_1

    @property
    def english_name(self):
        """Gets the english_name of this InlineResponse2007.  # noqa: E501


        :return: The english_name of this InlineResponse2007.  # noqa: E501
        :rtype: str
        """
        return self._english_name

    @english_name.setter
    def english_name(self, english_name):
        """Sets the english_name of this InlineResponse2007.


        :param english_name: The english_name of this InlineResponse2007.  # noqa: E501
        :type: str
        """

        self._english_name = english_name

    @property
    def name(self):
        """Gets the name of this InlineResponse2007.  # noqa: E501


        :return: The name of this InlineResponse2007.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse2007.


        :param name: The name of this InlineResponse2007.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2007, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2007):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
